### PR TITLE
Display all players points in the dom

### PR DESCRIPTION
**Pull request by iamzaidmohammed**
I displayed all the players point in the dom and removed all the console.logs

### CODE REVIEW

**Comment by sylfort** [comment]
looks really good, can we also add the image slice_of_cheese.jpg beside the number of points for each player?

**Comment by iamzaidmohammed** [comment]
> looks really good, can we also add the image slice_of_cheese.jpg beside the number of points for each player?

Okay lemme try and see

**Review by dominic-source — APPROVED** [review]
Great work here.

**Comment by sylfort** [comment]
Perfect!

**Pull request merged**
